# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: mayfiled-os
description: Mayfiled OS - A custom Aurora-based desktop image.

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - distrobox
        - htop
        - kate
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
      - scope: user
        install:
          - us.zoom.Zoom
          - com.spotify.Client
          - org.kde.kpat

  - type: signing

